"""agregar elevacion_grabado_mm a configuracion_maquina (issue 195)

Revision ID: 089e3a9446c8
Revises: c4189040785e
Create Date: 2026-09-14 22:26:57.905329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089e3a9446c8'
down_revision: Union[str, Sequence[str], None] = 'c4189040785e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default=4.0 (issue #195): calibrado a mano en el taller, 3mm de
    # material para corte / 7mm para grabado -- backfillea la fila existente
    # de configuracion_maquina en el mismo paso que agrega la columna.
    op.add_column(
        'configuracion_maquina',
        sa.Column('elevacion_grabado_mm', sa.Float(), server_default='4.0', nullable=False),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('configuracion_maquina', 'elevacion_grabado_mm')
    # ### end Alembic commands ###
