"""schema inicial (issue 22)

Revision ID: 0c7f863e72da
Revises:
Create Date: 2026-09-05 20:25:43.092381

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c7f863e72da"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "configuracion_maquina",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("laser_max_s", sa.Integer(), nullable=False),
        sa.Column("travel_feed_mm_min", sa.Integer(), nullable=False),
        sa.Column("potencia_modulo_w", sa.Float(), nullable=False),
        sa.Column("factor_utilizacion_laser", sa.Float(), nullable=False),
        sa.Column("punto_focal_mm", sa.Float(), nullable=False),
        sa.Column("velocidad_max_mm_min", sa.Integer(), nullable=False),
        sa.Column("aceleracion_mm_s2", sa.Float(), nullable=False),
        sa.Column("area_trabajo_ancho_mm", sa.Float(), nullable=True),
        sa.Column("area_trabajo_alto_mm", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "materiales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=60), nullable=False),
        sa.Column(
            "familia", sa.Enum("MADERA", "POLIMERO", "METAL", "OTRO", name="familia_material"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_table(
        "tarifas_historial",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("moneda", sa.String(length=10), nullable=False),
        sa.Column("tarifa_electrica_por_kwh", sa.Float(), nullable=True),
        sa.Column("tarifa_hora_maquina", sa.Float(), nullable=True),
        sa.Column(
            "vigente_desde",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "grupos_calibracion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grupo_calibracion_id", sa.String(length=120), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("espesor_mm", sa.Float(), nullable=False),
        sa.Column(
            "operacion", sa.Enum("CORTE", "GRABADO", name="operacion_grupo_calibracion"), nullable=False
        ),
        sa.Column("velocidad_mm_min", sa.Integer(), nullable=False),
        sa.Column("potencia_pct", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materiales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grupo_calibracion_id"),
        sa.UniqueConstraint(
            "material_id",
            "espesor_mm",
            "operacion",
            "velocidad_mm_min",
            "potencia_pct",
            name="uq_grupo_calibracion_combinacion",
        ),
    )
    op.create_table(
        "precios_material",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("espesor_mm", sa.Float(), nullable=False),
        sa.Column("precio_por_m2", sa.Float(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materiales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("material_id", "espesor_mm", name="uq_precio_material_espesor"),
    )
    op.create_table(
        "suites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("espesor_mm", sa.Float(), nullable=False),
        sa.Column("operacion", sa.Enum("CORTE", "GRABADO", name="operacion"), nullable=False),
        sa.Column("velocidades_mm_min", sa.JSON(), nullable=False),
        sa.Column("potencias_pct", sa.JSON(), nullable=False),
        sa.Column("pasadas", sa.Integer(), nullable=False),
        sa.Column("z_step_mm", sa.Float(), nullable=False),
        sa.Column("tamano_celda_mm", sa.Float(), nullable=False),
        sa.Column("espaciado_mm", sa.Float(), nullable=False),
        sa.Column("id_prefijo", sa.String(length=2), nullable=False),
        sa.Column("lote", sa.String(length=20), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("svg_storage_key", sa.Text(), nullable=True),
        sa.Column(
            "modo_grabado_svg",
            sa.Enum("CONTORNO", "RELLENO", "CONTORNO_Y_RELLENO", name="modo_grabado_svg"),
            nullable=True,
        ),
        sa.Column("svg_resolucion_relleno_mm", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materiales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fichas_parametro",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grupo_calibracion_id", sa.Integer(), nullable=False),
        sa.Column("costo_estandar_total", sa.Float(), nullable=True),
        sa.Column("estado", sa.Enum("OFICIAL", "EN_REVISION", name="estado_ficha"), nullable=False),
        sa.Column("fecha_validacion", sa.Date(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grupo_calibracion_id"],
            ["grupos_calibracion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grupo_calibracion_id"),
    )
    op.create_table(
        "final_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("grupo_calibracion_id", sa.Integer(), nullable=False),
        sa.Column("ejecucion", sa.Integer(), nullable=False),
        sa.Column("repeticiones", sa.Integer(), nullable=False),
        sa.Column("pasadas", sa.Integer(), nullable=False),
        sa.Column("z_step_mm", sa.Float(), nullable=False),
        sa.Column("tamano_celda_mm", sa.Float(), nullable=False),
        sa.Column("espaciado_mm", sa.Float(), nullable=False),
        sa.Column("id_prefijo", sa.String(length=2), nullable=False),
        sa.Column("lote", sa.String(length=20), nullable=False),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grupo_calibracion_id"],
            ["grupos_calibracion.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("grupo_calibracion_id", "ejecucion", name="uq_final_run_ejecucion"),
    )
    op.create_table(
        "registros",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("corrida_id", sa.String(length=150), nullable=False),
        sa.Column("suite_id", sa.Integer(), nullable=True),
        sa.Column("final_run_id", sa.Integer(), nullable=True),
        sa.Column("fecha", sa.Date(), nullable=False),
        sa.Column("lote", sa.String(length=20), nullable=False),
        sa.Column("kwh_corrida_medido", sa.Float(), nullable=True),
        sa.Column("tiempo_real_corrida_s", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(suite_id IS NOT NULL) != (final_run_id IS NOT NULL)", name="ck_registro_origen_unico"
        ),
        sa.ForeignKeyConstraint(
            ["final_run_id"],
            ["final_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["suites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("corrida_id"),
    )
    op.create_table(
        "mediciones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registro_id", sa.Integer(), nullable=False),
        sa.Column("id_prueba", sa.String(length=20), nullable=False),
        sa.Column("velocidad_mm_min", sa.Integer(), nullable=False),
        sa.Column("potencia_pct", sa.Integer(), nullable=False),
        sa.Column("pasadas", sa.Integer(), nullable=False),
        sa.Column("x_mm", sa.Float(), nullable=False),
        sa.Column("y_mm", sa.Float(), nullable=False),
        sa.Column("tamano_celda_mm", sa.Float(), nullable=False),
        sa.Column("area_material_mm2", sa.Float(), nullable=False),
        sa.Column("tiempo_estimado_celda_s", sa.Float(), nullable=False),
        sa.Column("corte_pasante", sa.Boolean(), nullable=True),
        sa.Column("carbonizacion_1a5", sa.SmallInteger(), nullable=True),
        sa.Column("foto_storage_key", sa.Text(), nullable=True),
        sa.Column("notas", sa.Text(), nullable=True),
        sa.Column("kwh_celda", sa.Float(), nullable=True),
        sa.Column("costo_energia_celda", sa.Float(), nullable=True),
        sa.Column("costo_material_celda", sa.Float(), nullable=True),
        sa.Column("tiempo_maquina_celda_s", sa.Float(), nullable=True),
        sa.Column("costo_tiempo_maquina_celda", sa.Float(), nullable=True),
        sa.Column("costo_total_celda", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["registro_id"],
            ["registros.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registro_id", "id_prueba", name="uq_medicion_por_registro"),
    )
    op.create_table(
        "candidatos_final_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("medicion_id", sa.Integer(), nullable=False),
        sa.Column(
            "marcado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["medicion_id"],
            ["mediciones.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("medicion_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("candidatos_final_run")
    op.drop_table("mediciones")
    op.drop_table("registros")
    op.drop_table("final_runs")
    op.drop_table("fichas_parametro")
    op.drop_table("suites")
    op.drop_table("precios_material")
    op.drop_table("grupos_calibracion")
    op.drop_table("tarifas_historial")
    op.drop_table("materiales")
    op.drop_table("configuracion_maquina")
    # ### end Alembic commands ###
