"""indexar columnas FK sin cubrir por unique constraint

Revision ID: 5332a2590df1
Revises: bcabc60606cd
Create Date: 2026-09-05 22:03:18.665955

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5332a2590df1"
down_revision: str | Sequence[str] | None = "bcabc60606cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_registros_final_run_id"), "registros", ["final_run_id"], unique=False)
    op.create_index(op.f("ix_registros_suite_id"), "registros", ["suite_id"], unique=False)
    op.create_index(op.f("ix_suites_material_id"), "suites", ["material_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suites_material_id"), table_name="suites")
    op.drop_index(op.f("ix_registros_suite_id"), table_name="registros")
    op.drop_index(op.f("ix_registros_final_run_id"), table_name="registros")
    # ### end Alembic commands ###
