"""agregar gcode_storage_key a registros

Revision ID: 5e5373f852f5
Revises: 5332a2590df1
Create Date: 2026-09-05 22:19:29.503263

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e5373f852f5"
down_revision: str | Sequence[str] | None = "5332a2590df1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("registros", sa.Column("gcode_storage_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("registros", "gcode_storage_key")
    # ### end Alembic commands ###
