"""reemplazar costo_estandar_total por costos normalizados por mm/mm2

Revision ID: c4189040785e
Revises: d599494624d8
Create Date: 2026-09-10 20:16:53.110398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4189040785e'
down_revision: Union[str, Sequence[str], None] = 'd599494624d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fichas_parametro', sa.Column('costo_por_mm', sa.Float(), nullable=True))
    op.add_column('fichas_parametro', sa.Column('tiempo_por_mm_s', sa.Float(), nullable=True))
    op.add_column('fichas_parametro', sa.Column('costo_por_mm2', sa.Float(), nullable=True))
    op.add_column('fichas_parametro', sa.Column('tiempo_por_mm2_s', sa.Float(), nullable=True))
    op.add_column('fichas_parametro', sa.Column('material_costo_pendiente', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('fichas_parametro', 'costo_estandar_total')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fichas_parametro', sa.Column('costo_estandar_total', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('fichas_parametro', 'material_costo_pendiente')
    op.drop_column('fichas_parametro', 'tiempo_por_mm2_s')
    op.drop_column('fichas_parametro', 'costo_por_mm2')
    op.drop_column('fichas_parametro', 'tiempo_por_mm_s')
    op.drop_column('fichas_parametro', 'costo_por_mm')
    # ### end Alembic commands ###
