"""agregar proyectos de diseno del editor (issue 18)

Revision ID: d599494624d8
Revises: 6df74a2f0955
Create Date: 2026-09-07 18:42:58.000126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd599494624d8'
down_revision: Union[str, Sequence[str], None] = '6df74a2f0955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos_diseno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('ficha_parametro_id', sa.Integer(), nullable=True),
    sa.Column('objetos', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ficha_parametro_id'], ['fichas_parametro.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyectos_diseno_ficha_parametro_id'), 'proyectos_diseno', ['ficha_parametro_id'], unique=False)
    op.create_index(op.f('ix_proyectos_diseno_material_id'), 'proyectos_diseno', ['material_id'], unique=False)
    op.create_table('proyecto_diseno_exportaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('gcode_storage_key', sa.Text(), nullable=False),
    sa.Column('exportado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos_diseno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proyecto_diseno_exportaciones_proyecto_id'), 'proyecto_diseno_exportaciones', ['proyecto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proyecto_diseno_exportaciones_proyecto_id'), table_name='proyecto_diseno_exportaciones')
    op.drop_table('proyecto_diseno_exportaciones')
    op.drop_index(op.f('ix_proyectos_diseno_material_id'), table_name='proyectos_diseno')
    op.drop_index(op.f('ix_proyectos_diseno_ficha_parametro_id'), table_name='proyectos_diseno')
    op.drop_table('proyectos_diseno')
    # ### end Alembic commands ###
