"""agregar foto_bateria_storage_key a registros

Revision ID: f770b9e70c4e
Revises: 5e5373f852f5
Create Date: 2026-09-06 00:53:49.575341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f770b9e70c4e'
down_revision: Union[str, Sequence[str], None] = '5e5373f852f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros', sa.Column('foto_bateria_storage_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registros', 'foto_bateria_storage_key')
    # ### end Alembic commands ###
