material: MDF Trupan
espesor_mm: 3
operacion: corte
velocidades_mm_min:
  - 150
  - 180
  - 210
  - 240
potencias_pct:
  - 85
  - 100
pasadas: 2
tamano_celda_mm: 15
espaciado_mm: 3.5
id_prefijo: C
lote: L01
svg_path: data/svgs/simbolo-flux-negro-mtlxpstx.svg
machine:
  laser_max_s: 10000
  travel_feed_mm_min: 3000
