material: MDF Trupan
espesor_mm: 3
operacion: corte
velocidades_mm_min:
  - 80
potencias_pct:
  - 100
pasadas: 6
tamano_celda_mm: 15
espaciado_mm: 3.5
id_prefijo: C
lote: L03
svg_path: data/svgs/simbolo-flux-negro-mtlxpstx.svg
