material: MDF Comercial
espesor_mm: 3
operacion: corte
velocidades_mm_min:
  - 230
  - 240
  - 250
potencias_pct:
  - 100
pasadas: 3
tamano_celda_mm: 15
espaciado_mm: 3.5
id_prefijo: C
lote: L12
svg_path: data/svgs/simbolo-flux-negro-mtlxpstx.svg
