material: MDF Comercial
espesor_mm: 3
operacion: grabado
velocidades_mm_min:
  - 1000
  - 1250
  - 1500
  - 1750
  - 2000
potencias_pct:
  - 20
  - 35
  - 50
  - 65
  - 80
  - 100
pasadas: 1
tamano_celda_mm: 5
espaciado_mm: 3
id_prefijo: G
lote: L02
